-- =====================================================================
-- DeelMap Community Forum — foundation migration
-- =====================================================================
-- Run in Supabase SQL editor against the Marketplace database.
--
-- VERIFY BEFORE RUNNING:
--   1. select id from public.users limit 1;            -- expects uuid
--   2. select id from public.properties limit 1;       -- expects uuid
--   3. select id from public.wholesale_deals limit 1;  -- expects uuid
--   4. select * from pg_available_extensions where name = 'ltree';
--
-- If any of those fail, halt and report — the FK declarations below
-- assume uuid PKs on users / properties / wholesale_deals.
--
-- Privacy wall: community_profiles.user_id is the only link between
-- a real account and a community identity. We revoke SELECT/UPDATE on
-- that column for the anon and authenticated roles. Only the
-- service_role (used by Next.js API routes) can read it. API route
-- handlers MUST NEVER return user_id in a response payload.
-- =====================================================================

begin;

create extension if not exists ltree;
create extension if not exists citext;

-- ─── TABLES ───────────────────────────────────────────────────────────

-- Tier thresholds (admin-editable)
create table public.community_tiers (
  id          bigint generated by default as identity primary key,
  slug        text   not null unique,
  name        text   not null,
  min_equity  int    not null,
  sort_order  int    not null default 0,
  created_at  timestamptz not null default now()
);

-- Lots (sub-communities; admin-editable per Phase 2)
create table public.community_lots (
  id                 bigint generated by default as identity primary key,
  slug               citext not null unique,
  name               text   not null,
  category           text   not null check (category in
                       ('real_estate','lending','finance','contractors','markets')),
  description        text,
  accent_color       text,
  member_count       int    not null default 0,
  post_count         int    not null default 0,
  min_equity_to_post int    not null default 0,
  sort_order         int    not null default 0,
  is_active          boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index idx_community_lots_category on public.community_lots (category, sort_order);

-- Community profiles — privacy wall via REVOKE on user_id (below)
create table public.community_profiles (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null unique references public.users(id) on delete cascade,
  handle              citext not null unique check (
                        length(handle) between 3 and 24
                        and handle ~ '^[a-z0-9_]+$'
                        and handle not in
                          ('admin','deelmap','staff','mod','moderator','system',
                           'support','root','official','help','team')
                      ),
  display_name        text,
  bio                 text check (length(bio) <= 500),
  avatar_url          text,
  equity_score        int not null default 0,
  tier_id             bigint references public.community_tiers(id),
  role_badge          text check (role_badge in
                        ('lender','contractor','agent','principal','wholesaler')),
  is_moderator        boolean not null default false,
  is_shadowbanned     boolean not null default false,
  handle_changed_at   timestamptz,
  joined_at           timestamptz not null default now(),
  last_seen_at        timestamptz
);

create index idx_community_profiles_equity on public.community_profiles (equity_score desc);
create index idx_community_profiles_handle on public.community_profiles (handle);

-- PRIVACY WALL — the link between real identity and community identity.
-- Only service_role (Next.js API routes) can read or update user_id.
revoke select (user_id) on public.community_profiles from anon, authenticated;
revoke update (user_id) on public.community_profiles from anon, authenticated;

-- Lot subscriptions (My Lots)
create table public.community_lot_subscriptions (
  profile_id     uuid   not null references public.community_profiles(id) on delete cascade,
  lot_id         bigint not null references public.community_lots(id)     on delete cascade,
  subscribed_at  timestamptz not null default now(),
  primary key (profile_id, lot_id)
);

-- Posts — polymorphic deal link via two nullable FKs + check constraint
create table public.community_posts (
  id                uuid primary key default gen_random_uuid(),
  slug              citext not null unique,
  lot_id            bigint not null references public.community_lots(id) on delete cascade,
  author_id         uuid   not null references public.community_profiles(id) on delete cascade,
  title             text   not null check (length(title) between 8 and 200),
  body              text,
  property_id       uuid references public.properties(id)       on delete set null,
  wholesale_deal_id uuid references public.wholesale_deals(id)  on delete set null,
  market_tag        text,
  score             int    not null default 0,
  hot_score         double precision not null default 0,
  comment_count     int    not null default 0,
  is_pinned         boolean not null default false,
  is_locked         boolean not null default false,
  is_removed        boolean not null default false,
  removed_reason    text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint chk_one_deal_link check (property_id is null or wholesale_deal_id is null)
);

create index idx_community_posts_lot_hot      on public.community_posts (lot_id, hot_score desc) where is_removed = false;
create index idx_community_posts_lot_new      on public.community_posts (lot_id, created_at desc) where is_removed = false;
create index idx_community_posts_hot_global   on public.community_posts (hot_score desc) where is_removed = false;
create index idx_community_posts_new_global   on public.community_posts (created_at desc) where is_removed = false;
create index idx_community_posts_author       on public.community_posts (author_id);
create index idx_community_posts_property     on public.community_posts (property_id)       where property_id is not null;
create index idx_community_posts_wholesale    on public.community_posts (wholesale_deal_id) where wholesale_deal_id is not null;
create index idx_community_posts_pinned       on public.community_posts (is_pinned)         where is_pinned;

-- Comments — ltree path for unlimited threading, depth capped at 8 in trigger
create table public.community_comments (
  id          uuid primary key default gen_random_uuid(),
  post_id     uuid not null references public.community_posts(id)     on delete cascade,
  author_id   uuid not null references public.community_profiles(id)  on delete cascade,
  parent_id   uuid references public.community_comments(id) on delete cascade,
  body        text not null check (length(body) between 1 and 8000),
  path        ltree not null,
  depth       int not null check (depth between 0 and 8),
  score       int not null default 0,
  is_removed  boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index idx_community_comments_post   on public.community_comments (post_id, created_at);
create index idx_community_comments_path   on public.community_comments using gist (path);
create index idx_community_comments_author on public.community_comments (author_id);

-- Votes — ledger; one row per (profile, target). Value -1 or 1; absence = no vote.
create table public.community_votes (
  profile_id   uuid     not null references public.community_profiles(id) on delete cascade,
  target_type  text     not null check (target_type in ('post','comment')),
  target_id    uuid     not null,
  value        smallint not null check (value in (-1, 1)),
  created_at   timestamptz not null default now(),
  primary key (profile_id, target_type, target_id)
);

create index idx_community_votes_target on public.community_votes (target_type, target_id);

-- Equity events — ledger; equity_score on profile is the denormalized cache
create table public.community_equity_events (
  id          bigint generated by default as identity primary key,
  profile_id  uuid not null references public.community_profiles(id) on delete cascade,
  delta       int  not null,
  reason      text not null,
  ref_type    text,
  ref_id      text,
  created_at  timestamptz not null default now()
);

create index idx_community_equity_events_profile on public.community_equity_events (profile_id, created_at desc);

-- Verifications — mirrors seller_applications shape; separate concern.
create table public.community_verifications (
  id                uuid primary key default gen_random_uuid(),
  profile_id        uuid not null references public.community_profiles(id) on delete cascade,
  role              text not null check (role in ('lender','contractor','agent','principal','wholesaler')),
  legal_name        text not null,
  credential_type   text,
  credential_number text,
  jurisdiction      text,
  document_urls     text[],
  notes             text,
  status            text not null default 'pending'
                      check (status in ('pending','approved','rejected')),
  admin_notes       text,
  reviewed_by       bigint,
  reviewed_at       timestamptz,
  submitted_at      timestamptz not null default now()
);

create index idx_community_verifications_status  on public.community_verifications (status, submitted_at);
create index idx_community_verifications_profile on public.community_verifications (profile_id);

-- Saves (bookmarks)
create table public.community_saves (
  profile_id uuid not null references public.community_profiles(id) on delete cascade,
  post_id    uuid not null references public.community_posts(id)    on delete cascade,
  saved_at   timestamptz not null default now(),
  primary key (profile_id, post_id)
);

-- Notifications (polling-driven; Realtime is v2)
create table public.community_notifications (
  id              uuid primary key default gen_random_uuid(),
  profile_id      uuid not null references public.community_profiles(id) on delete cascade,
  type            text not null check (type in
                    ('comment_reply','post_reply','mention','verification_status','mod_action')),
  title           text not null,
  body            text,
  ref_post_id     uuid references public.community_posts(id)    on delete cascade,
  ref_comment_id  uuid references public.community_comments(id) on delete cascade,
  is_read         boolean not null default false,
  created_at      timestamptz not null default now()
);

create index idx_community_notifications_unread
  on public.community_notifications (profile_id, is_read, created_at desc);

-- Reports (moderation queue)
create table public.community_reports (
  id           uuid primary key default gen_random_uuid(),
  reporter_id  uuid not null references public.community_profiles(id) on delete cascade,
  target_type  text not null check (target_type in ('post','comment','profile')),
  target_id    uuid not null,
  reason       text not null,
  details      text,
  status       text not null default 'open'
                 check (status in ('open','reviewed','dismissed')),
  reviewed_by  bigint,
  reviewed_at  timestamptz,
  created_at   timestamptz not null default now()
);

create index idx_community_reports_status on public.community_reports (status, created_at);

-- ─── FUNCTIONS ────────────────────────────────────────────────────────

-- Reddit-style hot score (~12hr half-life via 45000 divisor against epoch seconds)
create or replace function public.community_hot_score(p_score int, p_created_at timestamptz)
returns double precision language sql immutable as $$
  select
    log(greatest(abs(p_score), 1)) * sign(p_score)::double precision
    + extract(epoch from (p_created_at - timestamp '2025-01-01 00:00:00')) / 45000.0
$$;

-- Award equity: append to ledger, bump denormalized score, recompute tier.
-- Self-vote exclusion is the CALLER's responsibility (see vote trigger below).
create or replace function public.community_award_equity(
  p_profile_id uuid,
  p_delta      int,
  p_reason     text,
  p_ref_type   text default null,
  p_ref_id     text default null
) returns void language plpgsql as $$
declare
  v_new_score int;
  v_tier_id   bigint;
begin
  if p_delta = 0 or p_profile_id is null then return; end if;

  insert into public.community_equity_events (profile_id, delta, reason, ref_type, ref_id)
  values (p_profile_id, p_delta, p_reason, p_ref_type, p_ref_id);

  update public.community_profiles
    set equity_score = equity_score + p_delta
    where id = p_profile_id
    returning equity_score into v_new_score;

  select id into v_tier_id from public.community_tiers
    where min_equity <= v_new_score
    order by min_equity desc limit 1;

  update public.community_profiles set tier_id = v_tier_id where id = p_profile_id;
end $$;

-- Apply vote: insert / update / clear (value = 0). Idempotent.
create or replace function public.community_apply_vote(
  p_profile_id  uuid,
  p_target_type text,
  p_target_id   uuid,
  p_value       smallint
) returns smallint language plpgsql as $$
declare
  v_existing smallint;
begin
  select value into v_existing
    from public.community_votes
    where profile_id = p_profile_id
      and target_type = p_target_type
      and target_id = p_target_id;

  if p_value = 0 then
    delete from public.community_votes
      where profile_id = p_profile_id
        and target_type = p_target_type
        and target_id = p_target_id;
    return 0;
  end if;

  insert into public.community_votes (profile_id, target_type, target_id, value)
  values (p_profile_id, p_target_type, p_target_id, p_value)
  on conflict (profile_id, target_type, target_id)
    do update set value = excluded.value, created_at = now();
  return p_value;
end $$;

-- Vote trigger: maintain target score + hot_score, award equity (excluding self-votes)
create or replace function public.community_votes_after_change()
returns trigger language plpgsql as $$
declare
  v_author     uuid;
  v_created_at timestamptz;
  v_delta_score int;
  v_old_eq     int;
  v_new_eq     int;
  v_eq_delta   int;
begin
  if TG_OP = 'INSERT' then
    v_delta_score := NEW.value;
  elsif TG_OP = 'UPDATE' then
    v_delta_score := NEW.value - OLD.value;
  else  -- DELETE
    v_delta_score := -OLD.value;
  end if;

  if NEW.target_type is not null then
    if NEW.target_type = 'post' then
      update public.community_posts
        set score = score + v_delta_score,
            hot_score = public.community_hot_score(score + v_delta_score, created_at)
        where id = NEW.target_id
        returning author_id, created_at into v_author, v_created_at;
    else
      update public.community_comments
        set score = score + v_delta_score
        where id = NEW.target_id
        returning author_id into v_author;
    end if;
  else
    if OLD.target_type = 'post' then
      update public.community_posts
        set score = score + v_delta_score,
            hot_score = public.community_hot_score(score + v_delta_score, created_at)
        where id = OLD.target_id
        returning author_id into v_author;
    else
      update public.community_comments
        set score = score + v_delta_score
        where id = OLD.target_id
        returning author_id into v_author;
    end if;
  end if;

  -- Equity scoring (self-vote excluded)
  if v_author is not null then
    declare v_voter uuid := coalesce(NEW.profile_id, OLD.profile_id);
            v_ttype text := coalesce(NEW.target_type, OLD.target_type);
            v_old   smallint := coalesce(OLD.value, 0);
            v_new   smallint := coalesce(NEW.value, 0);
            v_old_pts int;
            v_new_pts int;
    begin
      if v_voter <> v_author then
        -- per-vote equity: post +5/-2, comment +2/-1
        v_old_pts := case v_old when 1 then case when v_ttype='post' then 5 else 2 end
                              when -1 then case when v_ttype='post' then -2 else -1 end
                              else 0 end;
        v_new_pts := case v_new when 1 then case when v_ttype='post' then 5 else 2 end
                              when -1 then case when v_ttype='post' then -2 else -1 end
                              else 0 end;
        v_eq_delta := v_new_pts - v_old_pts;
        if v_eq_delta <> 0 then
          perform public.community_award_equity(v_author, v_eq_delta,
            'vote_' || v_ttype, v_ttype, coalesce(NEW.target_id, OLD.target_id)::text);
        end if;
      end if;
    end;
  end if;

  return null;
end $$;

create trigger trg_community_votes_after_change
  after insert or update or delete on public.community_votes
  for each row execute function public.community_votes_after_change();

-- Post insert: +1 equity to author, bump lot post_count, set hot_score
create or replace function public.community_posts_before_insert()
returns trigger language plpgsql as $$
begin
  NEW.hot_score := public.community_hot_score(coalesce(NEW.score, 0), coalesce(NEW.created_at, now()));
  return NEW;
end $$;

create trigger trg_community_posts_before_insert
  before insert on public.community_posts
  for each row execute function public.community_posts_before_insert();

create or replace function public.community_posts_after_insert()
returns trigger language plpgsql as $$
begin
  update public.community_lots set post_count = post_count + 1 where id = NEW.lot_id;
  perform public.community_award_equity(NEW.author_id, 1, 'post_created', 'post', NEW.id::text);
  return null;
end $$;

create trigger trg_community_posts_after_insert
  after insert on public.community_posts
  for each row execute function public.community_posts_after_insert();

-- Comment insert: derive ltree path + depth, +1 equity, bump post comment_count
create or replace function public.community_comments_before_insert()
returns trigger language plpgsql as $$
declare
  v_parent_path  ltree;
  v_parent_depth int;
  v_label        text;
begin
  -- ltree labels must match [A-Za-z0-9_]; uuid hyphens are not allowed.
  v_label := replace(NEW.id::text, '-', '_');
  if NEW.parent_id is null then
    NEW.path  := ('root.' || v_label)::ltree;
    NEW.depth := 0;
  else
    select path, depth into v_parent_path, v_parent_depth
      from public.community_comments where id = NEW.parent_id;
    if v_parent_path is null then
      raise exception 'Parent comment % not found', NEW.parent_id;
    end if;
    NEW.path  := v_parent_path || v_label::ltree;
    NEW.depth := least(v_parent_depth + 1, 8);
  end if;
  return NEW;
end $$;

create trigger trg_community_comments_before_insert
  before insert on public.community_comments
  for each row execute function public.community_comments_before_insert();

create or replace function public.community_comments_after_insert()
returns trigger language plpgsql as $$
begin
  update public.community_posts set comment_count = comment_count + 1 where id = NEW.post_id;
  perform public.community_award_equity(NEW.author_id, 1, 'comment_created', 'comment', NEW.id::text);
  return null;
end $$;

create trigger trg_community_comments_after_insert
  after insert on public.community_comments
  for each row execute function public.community_comments_after_insert();

-- Verification approved → award +50 equity once
create or replace function public.community_verifications_after_update()
returns trigger language plpgsql as $$
begin
  if NEW.status = 'approved' and OLD.status is distinct from 'approved' then
    update public.community_profiles
      set role_badge = NEW.role
      where id = NEW.profile_id;
    perform public.community_award_equity(NEW.profile_id, 50, 'verification_approved',
      'verification', NEW.id::text);
  end if;
  return null;
end $$;

create trigger trg_community_verifications_after_update
  after update on public.community_verifications
  for each row execute function public.community_verifications_after_update();

-- ─── SEED ─────────────────────────────────────────────────────────────

insert into public.community_tiers (slug, name, min_equity, sort_order) values
  ('newcomer',  'Newcomer',  0,     1),
  ('member',    'Member',    100,   2),
  ('insider',   'Insider',   1000,  3),
  ('principal', 'Principal', 5000,  4),
  ('operator',  'Operator',  15000, 5);

insert into public.community_lots (slug, name, category, accent_color, sort_order) values
  -- Real Estate
  ('wholesaling',        'Wholesaling',         'real_estate', '#2563EB', 1),
  ('fix-and-flip',       'Fix & Flip',          'real_estate', '#2563EB', 2),
  ('brrrr',              'BRRRR',               'real_estate', '#2563EB', 3),
  ('multifamily',        'Multifamily',         'real_estate', '#2563EB', 4),
  ('commercial',         'Commercial',          'real_estate', '#2563EB', 5),
  ('land',               'Land',                'real_estate', '#2563EB', 6),
  ('new-construction',   'New Construction',    'real_estate', '#2563EB', 7),
  -- Lending & Capital
  ('dscr-loans',         'DSCR Loans',          'lending',     '#0F6E56', 1),
  ('hard-money',         'Hard Money',          'lending',     '#0F6E56', 2),
  ('bridge-gap',         'Bridge & Gap',        'lending',     '#0F6E56', 3),
  ('private-capital',    'Private Capital',     'lending',     '#0F6E56', 4),
  ('conventional',       'Conventional',        'lending',     '#0F6E56', 5),
  ('construction-draws', 'Construction Draws',  'lending',     '#0F6E56', 6),
  -- Finance & Strategy
  ('underwriting',       'Underwriting',        'finance',     '#D03839', 1),
  ('tax-strategy',       'Tax Strategy',        'finance',     '#D03839', 2),
  ('entity-structure',   'Entity Structure',    'finance',     '#D03839', 3),
  ('bookkeeping',        'Bookkeeping',         'finance',     '#D03839', 4),
  ('exits-1031',         'Exits & 1031',        'finance',     '#D03839', 5),
  -- Contractors & Trades
  ('general-contracting','General Contracting', 'contractors', '#B5620A', 1),
  ('plumbing',           'Plumbing',            'contractors', '#B5620A', 2),
  ('electrical',         'Electrical',          'contractors', '#B5620A', 3),
  ('hvac',               'HVAC',                'contractors', '#B5620A', 4),
  ('roofing-exterior',   'Roofing & Exterior',  'contractors', '#B5620A', 5),
  ('foundation',         'Foundation',          'contractors', '#B5620A', 6),
  ('materials-sourcing', 'Materials & Sourcing','contractors', '#B5620A', 7),
  -- Markets (seed a starter set; admin grows the list as new metros cross the threshold)
  ('lexington-ky',       'Lexington, KY',       'markets',     '#7C3AED', 1),
  ('dfw-tx',             'DFW, TX',             'markets',     '#7C3AED', 2),
  ('tampa-fl',           'Tampa, FL',           'markets',     '#7C3AED', 3),
  ('phoenix-az',         'Phoenix, AZ',         'markets',     '#7C3AED', 4),
  ('memphis-tn',         'Memphis, TN',         'markets',     '#7C3AED', 5),
  ('atlanta-ga',         'Atlanta, GA',         'markets',     '#7C3AED', 6);

commit;

-- =====================================================================
-- POST-MIGRATION (run separately in Supabase dashboard, not SQL):
--   • Create private Storage bucket `community-verifications` (private, RLS on).
--     Used for verification document uploads (NMLS PDFs, license images, COI).
--   • Create public Storage bucket `community-uploads` (public-read).
--     Used for in-post image attachments and avatars.
-- =====================================================================
