-- chat_user_preferences: per-user, per-conversation preferences (pin, block, mark unread, etc.)
-- Run in Supabase SQL Editor if the table is missing. Required for Messages block/pin/unread and Settings blocked list.

CREATE TABLE IF NOT EXISTS public.chat_user_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('buyer', 'seller')),
  actor_id TEXT NOT NULL,
  is_done BOOLEAN NOT NULL DEFAULT FALSE,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  mark_unread BOOLEAN NOT NULL DEFAULT FALSE,
  last_outbound_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (conversation_id, actor_type, actor_id)
);

CREATE INDEX IF NOT EXISTS idx_chat_user_preferences_conversation_actor
  ON public.chat_user_preferences (conversation_id, actor_type, actor_id);
CREATE INDEX IF NOT EXISTS idx_chat_user_preferences_actor_blocked
  ON public.chat_user_preferences (actor_type, actor_id) WHERE is_blocked = TRUE;

COMMENT ON TABLE public.chat_user_preferences IS 'Per-user preferences for chat conversations: pin, block, mark unread.';
