-- Message actions: soft delete, reply/quote, and reporting.
-- Run once in the Supabase SQL editor (Deelmap project) before deploying.

-- 1. Soft delete + message-to-message reply reference (messages.id is bigint)
alter table public.messages
  add column if not exists is_deleted boolean not null default false,
  add column if not exists deleted_at timestamptz,
  add column if not exists reply_to_id bigint references public.messages(id) on delete set null;

-- 2. Reports — flagged messages escalate here for admin review (scam/abuse trail)
create table if not exists public.message_reports (
  id              bigint generated by default as identity primary key,
  message_id      bigint not null references public.messages(id) on delete cascade,
  conversation_id bigint,
  reporter_id     text not null,                   -- who reported (buyer uuid / user id)
  reported_sender text,                            -- the reported message's sender_id
  reason          text,                            -- category: spam | scam | abuse | other
  details         text,                            -- optional free text from the reporter
  status          text not null default 'open',    -- open | reviewed | dismissed | actioned
  created_at      timestamptz not null default now(),
  reviewed_at     timestamptz
);
create index if not exists message_reports_status_idx
  on public.message_reports (status, created_at desc);
